# Generated by Django 2.1.1 on 2018-09-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('species', models.CharField(max_length=64)),
                ('race', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=64)),
                ('age', models.DateField()),
                ('weight', models.IntegerField(null=True)),
                ('sterilized_castrated', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('img_main', models.ImageField(null=True, upload_to='')),
                ('img_main_alt', models.ImageField(null=True, upload_to='')),
                ('img_s', models.ImageField(null=True, upload_to='')),
                ('location', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('evidence_number', models.CharField(max_length=64)),
                ('admission_date', models.DateField()),
            ],
        ),
    ]
