# Generated by Django 2.1.1 on 2018-10-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budrys_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
