# Generated by Django 2.1.1 on 2018-09-14 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budrys_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='admission_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='animals',
            name='image',
            field=models.ImageField(default='img/None/no-img.jpg', upload_to='img/'),
        ),
    ]
