# Generated by Django 2.1.1 on 2018-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budrys_app', '0002_auto_20181001_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='race',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='sex',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='species',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='weight',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
