# Generated by Django 2.1.1 on 2018-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budrys_app', '0002_auto_20180914_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='evidence_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
