# Generated by Django 2.1.1 on 2018-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budrys_app', '0003_auto_20180914_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='age',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='img_main',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='img_main_alt',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='img_s',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
