# Generated by Django 2.1.1 on 2018-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budrys_app', '0005_auto_20180916_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='evidence_number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='img_main',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='img_main_alt',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='animals',
            name='location',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='animals',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='animals',
            name='race',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='animals',
            name='sex',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='animals',
            name='species',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='animals',
            name='sterilized_castrated',
            field=models.CharField(max_length=64),
        ),
    ]
