# Generated by Django 2.1.1 on 2018-09-17 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budrys_app', '0007_auto_20180917_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='admission_date',
            field=models.CharField(default=datetime.date.today, max_length=64),
        ),
    ]
